name: Ruff Formatting

on:
  pull_request:
    paths:
      - '**/*.py'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff formatting check
        run: |
          ruff check .

      - name: Upload Ruff report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ruff-report
          path: .ruff-report.json
